// This file is "main.dart"
import 'package:flutter_offline_mode/models/user.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';
import 'package:hive/hive.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'link.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'link.g.dart';

@freezed
class Link with _$Link {
  @HiveType(typeId: 0, adapterName: 'LinkAdapter')
  const factory Link({
    @HiveField(0) String? id,
    @HiveField(1) String? title,
    @HiveField(2) String? address,
    @HiveField(3) User? user,
  }) = _Link;

  factory Link.fromJson(Map<String, Object?> json) => _$LinkFromJson(json);
}
