// This file is "main.dart"
import 'package:flutter_offline_mode/models/user.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'link.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'link.g.dart';

@freezed
class Link with _$Link {
  const factory Link({
    String? id,
    String? title,
    String? address,
    User? user,
  }) = _Link;

  factory Link.fromJson(Map<String, Object?> json)
      => _$LinkFromJson(json);
}